module.exports = [
    {
      marca: 'Ford',
      modelo: 'Fiesta',
      color: 'Azul',
      anio: 2019,
      km: 20,
      precio: 150000,
      cuotas: 12,
      patente: 'APL123',
      vendido: false,
    },
    {
      marca: 'Toyota',
      modelo: 'Corolla',
      color: 'Blanco',
      anio: 2019,
      km: 0,
      precio: 100000,
      cuotas: 14,
      patente: 'JJK116',
      vendido: false,
    },
    {
      marca: 'Chevrolet',
      modelo: 'Cruze',
      color: 'Negro',
      anio: 2020,
      km: 0,
      precio: 100000,
      cuotas: 14,
      patente: 'JJK117',
      vendido: false,
    },
  ]

